#!/bin/bash
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#
#
# DESCRIPTION:
# This is the script runs a check to see if a file has been installed/created and has a timeout
#
#
# REQUIREMENTS:
#           - Jamf Pro
#           - macOS Clients running version 10.13 or later
#
# FEATURES:
#
# For more information, visit https://github.com/digitalconvergenceca/Mac_Admin_Jamf/tree/main/Scripts
#
# Written by: Trevor Leadley | Digital Convergence
#
#
# Revision History:
# YYYY-MM-DD: Details
# 2024-08-29: Created script
#
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Script Variables
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## Script Variables Jamf Pro
application_path="$4"
application_title="$5"
timeout="$6" # in seconds
ID="$7" # triggername of the policy you wish to trigger

## System Variables
getudid=$(system_profiler SPHardwareDataType | grep UUID | awk '{print $3}')
ComputerSerial=$( system_profiler SPHardwareDataType | grep Serial |  awk '{print $NF}' )
loggedInUser=$( scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }' )

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Function Commands
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # #
file_chk(){

until ! [ -f "$application_path" ];
do
  # When the timeout is equal to zero, show an error and leave the loop.
  if [ "$timeout" == 0 ]; then
    echo "ERROR: Timeout while waiting for the file /tmp/list.txt."
    exit 1
  fi
  sleep 1
    # Decrease the timeout of one
  ((timeout--))
done

if ! [ -f "$application_path" ]; then
 echo "Application has been installed"
 
 if [ ! -z "$ID" ]; then
    jamf policy -event $ID
 fi
 
 exit 0;
 
 fi

}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Commandline Actions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## Commands that need to be run
file_chk

exit 0
